#!/usr/bin/env node
// Generate an EBNF grammar for Dungeon commands from vocabulary.json.
//
// Output: js/llm/grammar.ebnf — used with Web-LLM's grammar-constrained
// decoding (response_format: { type: "grammar", grammar: <this file> }).
//
// The grammar covers Dungeon's full command syntax:
//   movement   ::= direction | GO direction | WALK direction | RUN direction
//   action     ::= verb [object_phrase] [preposition object_phrase]
//   meta       ::= INVENTORY | SCORE | LOOK | WAIT | AGAIN | ...
//   TELL       ::= TELL actor "<inner-command>"
//   ANSWER     ::= ANSWER "<word>"
//
// The LLM is expected to emit a JSON object; the `command` field is
// grammar-constrained, and `confidence` and `explanation` are free-form
// but type-constrained.
//
// Usage: node js/llm/generate-grammar.mjs

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const vocabPath = join(__dirname, 'vocabulary.json');
const outPath = join(__dirname, 'grammar.ebnf');

const v = JSON.parse(readFileSync(vocabPath, 'utf8'));

// EBNF helpers
function alt(words) {
  return words.map(w => `"${w}"`).join(' | ');
}

// Partition verbs: meta-verbs (standalone) vs action-verbs (take an object).
// We already have v.metaVerbs; remove those from v.verbs to get action verbs.
const metaSet = new Set(v.metaVerbs);
const actionVerbs = v.verbs.filter(w => !metaSet.has(w));

// Direction-taking verbs (these move you) — most can be omitted:
// the bare direction is also valid.
const moveVerbs = ['GO', 'WALK', 'RUN', 'PROCEED'];

// TELL and ANSWER have distinctive syntax: TELL actor "inner-command" and
// ANSWER "word". We special-case these.
const tellVerbs = ['TELL', 'COMMAND', 'REQUEST'];
const answerVerbs = ['ANSWER', 'RESPOND'];

// Filter out TELL/ANSWER and move verbs from actionVerbs — they get their
// own productions.
const specialVerbs = new Set([...tellVerbs, ...answerVerbs, ...moveVerbs]);
const ordinaryActionVerbs = actionVerbs.filter(v => !specialVerbs.has(v));

// INCANT takes a quoted spell
const incantVerbs = ['INCANT'];

// Emit the grammar
const lines = [];

lines.push('# Dungeon command grammar (EBNF, W3C XML notation).');
lines.push('# Auto-generated by js/llm/generate-grammar.mjs. Do not edit by hand.');
lines.push('# Covers the commands the Dungeon parser (parser.js) accepts.');
lines.push('# Used with Web-LLM response_format: { type: "grammar", grammar: <this> }.');
lines.push('');

// Top-level JSON envelope
lines.push('# --- JSON envelope ---');
lines.push('root ::= "{" ws ');
lines.push('           "\\"command\\"" ws ":" ws "\\"" command "\\"" ws "," ws');
lines.push('           "\\"confidence\\"" ws ":" ws confidence ws "," ws');
lines.push('           "\\"explanation\\"" ws ":" ws explanation ws');
lines.push('         "}"');
lines.push('');

lines.push('# --- Whitespace ---');
lines.push('ws  ::= ([ \\n\\t])*');
lines.push('sp  ::= " "');        // single mandatory space inside a command
lines.push('');

lines.push('# --- Confidence (0.0 to 1.0, one decimal place) ---');
lines.push('confidence ::= "0" | "0." ("0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9") | "1" | "1.0"');
lines.push('');

lines.push('# --- Explanation: a short JSON string (we trust the model to keep it short) ---');
lines.push('explanation ::= "\\"" exp_char* "\\""');
lines.push('exp_char    ::= [^"\\\\\\n\\r] | "\\\\\\"" | "\\\\\\\\" | "\\\\n"');
lines.push('');

lines.push('# --- Command top level ---');
lines.push('command ::= meta | movement | tell | answer | incant | action');
lines.push('');

lines.push('# --- Meta commands (standalone, no object) ---');
lines.push(`meta ::= (${alt(v.metaVerbs)})`);
lines.push('');

lines.push('# --- Movement ---');
lines.push('movement  ::= direction | move_verb sp direction');
lines.push(`move_verb ::= (${alt(moveVerbs)})`);
lines.push(`direction ::= (${alt(v.directions)})`);
lines.push('');

lines.push('# --- TELL actor "..." ---');
lines.push(`tell       ::= tell_verb sp actor sp "\\"" inner_command "\\""`);
lines.push(`tell_verb  ::= (${alt(tellVerbs)})`);
lines.push('actor      ::= ("ROBOT" | "THIEF" | "MASTER" | "CYCLOPS" | "DEMON" | "GHOST" | noun)');
lines.push('inner_command ::= (meta | movement | action)');
lines.push('');

lines.push('# --- ANSWER "..." ---');
lines.push(`answer       ::= answer_verb sp "\\"" word "\\""`);
lines.push(`answer_verb  ::= (${alt(answerVerbs)})`);
lines.push('word         ::= letter letter letter*');
lines.push('letter       ::= [A-Z] | [0-9]');
lines.push('');

lines.push('# --- INCANT "..." ---');
lines.push(`incant       ::= incant_verb sp "\\"" word (sp word)* "\\""`);
lines.push(`incant_verb  ::= (${alt(incantVerbs)})`);
lines.push('');

lines.push('# --- Ordinary action: VERB [OBJECT] [PREP OBJECT] ---');
lines.push('action       ::= action_verb (sp object_phrase (sp preposition sp object_phrase)?)?');
lines.push(`action_verb  ::= (${alt(ordinaryActionVerbs)})`);
lines.push('');

lines.push('# --- Object phrase: [adjective] noun, or a collective ---');
lines.push('object_phrase ::= (buzzword sp)* (adjective sp)? noun');
lines.push('                | collective (sp "EXCEPT" sp object_list)?');
lines.push('                | object_list');
lines.push('object_list   ::= object_one (sp? "," sp? object_one)* (sp? ("AND" | ",") sp? object_one)?');
lines.push('object_one    ::= (buzzword sp)* (adjective sp)? noun');
lines.push('collective    ::= "ALL" | "EVERYTHING" | "EVERYTHI" | "VALUABLES" | "VALUABLE" | "POSSESSIONS" | "POSSESSI"');
lines.push('');

lines.push('# --- Vocabulary ---');
lines.push(`buzzword    ::= ${alt(v.buzzwords)}`);
lines.push(`preposition ::= ${alt(v.prepositions)}`);
lines.push(`adjective   ::= ${alt(v.adjectives)}`);
lines.push(`noun        ::= ${alt(v.nouns)}`);
lines.push('');

lines.push('# --- End of grammar ---');

writeFileSync(outPath, lines.join('\n') + '\n');

process.stderr.write(
  `grammar.ebnf written (${lines.length} lines, ` +
  `${v.verbs.length} verbs, ${v.nouns.length} nouns, ${v.adjectives.length} adjectives)\n`
);
